# travis-ci.org configuration
language: c
env:
    global:
        - secure: "YP5bVNoYlLuwtLKDWhW7D4bexRWdYFPqz6J2DOuQAId4ids63JdGD7GOAZDfzizl1PtcoI3Kb97WWnFkPE2W6x/N4ad3K8lzIWZWx4kEpFRlbH7PJOF0Jt+rLXJzjkCW93XVC+vUY4bKAujT/iO8/B4lrxkX3/sCzILi7U5holE="
compiler:
    - gcc
    - clang
branches:
    only:
        - master
install:
    - sudo apt-get remove -qq autoconf automake autotools-dev libtool
    - ci/build-1-autotools.sh
    - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
    - cpanm --sudo Test::Command
script:
    - ci/build-2-install.sh
    - prove ci/test-*.pl
after_success:
    - ci/deploy-bintray.sh
