# travis-ci.org configuration
language: c
compiler:
  - gcc
  - clang
branches:
  only:
      - master
install:
    - sudo apt-get remove -qq autoconf automake autotools-dev libtool
    - ci/build-1-autotools.sh
    - cpanm Test::Command
script:
    - ci/build-2-install.sh
    - prove ci/test-*.pl
