language: generic

os:
  - linux

dist:
  - trusty
  - xenial

env:
  global:
    - secure: "CoI8hwHH1yfQoQxIfWGRS0WfTyScox+5aJn0fDDgz2uKrrIxmBvIw/WKX8wcSiV6fLmLuwgNkKqSM3hdO4qaG+JxfWcuEiZZHm+kxSGMkWbGb/fvAI+gHg8ldKyYttcIX71O5rlZiC2QpNKQi2v18S6pI5p8eqnx7DYx4YrmguQ="
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
    - secure: "C9ZJ9LYnuowRdF4D66KLfquimvu8GtRGIafwvCcGYKReEy8phlBdFsHlybkMBNYJNTJSM0j6wyo1lKTVGHxmpQDimjR7kmxUtawbhuJ5qOCBtFqNVh9lRQi7hC4+UOhvRsIcbV8HAJM5u/5RxGOfXCePK3a2DtiYv1d2NHToZN8="

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - libcap2-bin
      - libtest-command-perl
  coverity_scan:
    project:
      name: "schweikert/fping"
      description: "Build submitted via Travis CI"
    notification_email: david@schweikert.ch
    build_command:   "ci/build-3-compile.sh"
    branch_pattern: coverity_scan
    
install:
  - ci/build-2-test-command.sh
  - ci/build-3-prepare-macos.sh

script:
  - ci/build-4-compile.sh
  - ci/run-tests.sh
  - ci/deploy-bintray.sh

after_success:
  - ci/deploy-coveralls.sh

stages:
  - test
  - name: deploy
    if: branch = master OR branch = v4.x

jobs:
  include:
    #### STAGE: test
    - stage: test
      name: test trusty
      os: linux
      dist: trusty
      before_install:
        - ci/build-1-autotools.sh

    - name: test xenial
      os: linux
      dist: xenial

    - name: test macos
      os: osx

    #### STAGE: deploy
    - stage: deploy
      name: deploy
      os: linux
      dist: xenial
      env:
        - DO_DEPLOY=1
