# travis-ci.org configuration
language: c
compiler:
  - gcc
  - clang
branches:
  only:
      - master
before_install:
    - sudo apt-get remove -qq autoconf automake autotools-dev libtool
    - ci/build-1-autotools.sh
script:
    - ci/build-2-install.sh
    - ci/test-1.sh
